### ISSUE TITLE
xd design

### ISSUE THREAD

**Issue by shuyanglin** [g0v/vue.vtaiwan.tw#1]
http://adobe.ly/2dRDNQG

**Comment by audreyt** [comment]
原本的 Logo AI 檔在 https://trello.com/c/ly4luKGB/2-landing-page

**Comment by shuyanglin** [comment]
vTaiwan v2 
http://adobe.ly/2ddTD6O

**Comment by audreyt** [comment]
vTaiwan v4 https://xd.adobe.com/view/913afc4f-ee64-4872-ac54-aeda8883c4aa/

**Comment by yhsiang** [comment]
@shuyanglin  help to update a new xd file?

**Comment by shuyanglin** [comment]
https://xd.adobe.com/view/913afc4f-ee64-4872-ac54-aeda8883c4aa/

**Comment by audreyt** [comment]
It's 155MB so it took some time but it's now checked into the repo.

**Comment by audreyt** [comment]
For people without `git-lfs` installed, one can download it also from: http://audreyt.org/tmp/vTaiwan%20v4.xd

**Comment by yutin1987** [comment]
will show `Error loading document. Invalid document type.` when open v4.xd
ref. https://forums.adobe.com/thread/2119406

cc. @audreyt
