### ISSUE TITLE
全域導入jQuery?

### ISSUE THREAD

**Issue by bestian** [g0v/vue.vtaiwan.tw#14]
webpack的設定檔，在不同情境下會有出入
目前查到的解，均非針對webpack2 + vue2 server-side rendering
要如何針對vue.vTaiwan.tw(webpack2 + vue2 server-side rendering)設定呢?

**Comment by mark19891107** [comment]
這部分還在研究 囧
話說當初導入ssr的原因是因為要讓所有頁面都變成靜態頁面嗎＠＠？
有考慮用[https://github.com/chrisvfritz/prerender-spa-plugin](https://github.com/chrisvfritz/prerender-spa-plugin)完成嗎＠＠？

因為vuejs 的ssr 感覺還不是很完整 囧
(例如http request套件的vue-resources沒有SSR的版本，雖然後來改用axios有解)
再來就是因為已經導入Semantic-UI，如果不用jQuery 有很多特效無法完成

以上原因，就先放進jQuery了... 如果有影響到本來的規劃 那我們會再將它移除 感謝

**Comment by bestian** [comment]
我有提上vue.js臉書社團，有收集到一些可能的方案，但還沒時間測試
[https://www.facebook.com/groups/vuejs.tw/permalink/1232946623451734/](https://www.facebook.com/groups/vuejs.tw/permalink/1232946623451734/
)

ssr在我參與之前就設定了，所以詳情我也不清楚，大概是因為SEO以及每頁有獨立網址吧

目前Semantic-UI和jQuery都是引用外部資源，能動就沒什麼問題
我想不需要移除它們，仍然可以先用它們把想到的特效等等做出來
有時間再去把[外部資源]換成包進webpack的[內部資源]就好了

**Comment by mark19891107** [comment]
目前部署方式先暫時採用 gh-pages + pre-render 所以就先略過SSR的問題囉
SEO部分 og-title & og-image 已經在 https://github.com/g0v/vue.vtaiwan.tw/commit/9858f413b3dd2d89d0ff7ed0a8ccb4f77639a42d 加入
