### ISSUE TITLE
網站部署方式

### ISSUE THREAD

**Issue by mark19891107** [g0v/vue.vtaiwan.tw#24]
之前的專案設計風格看起來是用 vue 的 SSR 功能
但是這樣的話就要自己架設 nodejs server
如果我們已經採用discourse作為後端，那前端就可以放在github上而不用自己架設server
但是這樣SSR的功能就不能運作（或許要使用 pre-render 來實作）

總結來說方案有兩個

1. Github 純前端頁面 + Pre-render + talk.vtaiwan.tw 後端 Discourse
2. NodeJS + SSR + talk.vtaiwan.tw 後端 Discourse

以上問題，大家有什麼想法嗎 囧

順帶一題，已經設定好SSR部署環境的vue專案
似乎不能直接產生純靜態的網頁
[https://github.com/vuejs/vue-hackernews-2.0/issues/61](https://github.com/vuejs/vue-hackernews-2.0/issues/61) 
也就是說如果要採用方案1，可能要把SSR設定拿掉

**Comment by audreyt** [comment]
可以開一個拿掉 SSR 設定的 branch + pull request 比較容易討論？

**Comment by mark19891107** [comment]
可以參考 #25

**Comment by youchenlee** [comment]
從 g0v.tw 抄了 https://raw.githubusercontent.com/g0v/vue.vtaiwan.tw/master/deploy

目前可以下 `./deploy` （裡面會作 `yarn build:static` ）上到 gh-pages，網址是 http://vue.vtaiwan.tw/

**Comment by youchenlee** [comment]
已改為讓 prerender (`build:static`) 在 travis-ci 跑。
跑一次約 3 - 4 分鐘。

先將此 issue 關閉。如有其它問題再開 issue 囉。
