### ISSUE TITLE
http://vue.vtaiwan.tw/topic/sandbox 網址無法直連

### ISSUE THREAD

**Issue by youchenlee** [g0v/vue.vtaiwan.tw#26]
目前僅發現 http://vue.vtaiwan.tw/topic/sandbox 有問題，不確定還有沒有別的
（從首頁點入是可以的）

**Comment by mark19891107** [comment]
原因是出在這邊
https://github.com/g0v/vue.vtaiwan.tw/blob/master/build/webpack.static.config.js#L66-L82
因為當初prerender只是先嘗是可行性
可能要用什麼方法列出所有網址之類的
我會再補起來 Sorry

**Comment by youchenlee** [comment]
@mark19891107++

**Comment by mark19891107** [comment]
#32
