### ISSUE TITLE
進入每個議題的網址 /topic/*  底下會開始執行一個無窮迴圈的 requests

### ISSUE THREAD

**Issue by chairco** [g0v/vue.vtaiwan.tw#28]
看起來是到 talk.vtaiwan 去取得內容，但一直無窮迴圈抓。

<img width="1262" alt="2017-02-03 6 44 26" src="https://cloud.githubusercontent.com/assets/7709136/22588450/d63d3026-ea40-11e6-85da-f8f5f50e4efc.png">

**Comment by chairco** [comment]
如果沒有改掉，可能會灌爆 talk.vtaiwan 
<img width="657" alt="2017-02-04 10 57 14" src="https://cloud.githubusercontent.com/assets/7709136/22619320/548cb4c8-eb2d-11e6-954f-3c5b716e3aeb.png">

**Comment by smith02620** [comment]
此問題已解決
https://github.com/g0v/vue.vtaiwan.tw/commit/3712b63aeb52bc6dd8bef643ff2bcb9e8e6e6763
