### ISSUE TITLE
five-steps navigation doesn't work well on mobile version.

### ISSUE THREAD

**Issue by shuyanglin** [g0v/vue.vtaiwan.tw#29]
左邊欄位： 即將開始 意見徵集 研擬草案 送交審查 歷史案件
右邊欄位： 依據以上五個步驟，將相對應議題置入

選了左邊欄位的其中一個階段，右邊欄位 scroll to 那個階段
滑了右邊欄位到其中一個階段，左邊欄位的 highlight 隨之改變

**Comment by jokeum** [comment]
fixed https://github.com/g0v/vue.vtaiwan.tw/commit/ad2a98c4a57af5b4fda15dd3a3267151bb01e58b
