### ISSUE TITLE
搜尋列 點擊搜尋結果後 list不會消失

### ISSUE THREAD

**Issue by john5601** [g0v/vue.vtaiwan.tw#31]
輸入字串 點擊其中一向搜尋結果後 list不會消失
![default](https://cloud.githubusercontent.com/assets/7731119/22681709/aacfe292-ed49-11e6-9987-d90ec76fd0f8.PNG)

**Comment by youchenlee** [comment]
剛才 `./deploy` 後似乎就好了。應已經由其他朋友修復。

ref: 28e6e7f
