### ISSUE TITLE
FB share og data

### ISSUE THREAD

**Issue by youchenlee** [g0v/vue.vtaiwan.tw#35]
處理 FB share og data

**Comment by mark19891107** [comment]
已在 https://github.com/g0v/vue.vtaiwan.tw/commit/9858f413b3dd2d89d0ff7ed0a8ccb4f77639a42d 加入

**Comment by mark19891107** [comment]
![2017-02-13 10 58 35](https://cloud.githubusercontent.com/assets/7321879/22869607/68dac014-f1db-11e6-82f5-3e6b9da8a905.png)

目前長相，感覺缺少og:description 會讓畫面看起來空空的 囧

**Comment by youchenlee** [comment]
似乎壞掉了。
或可嘗試： https://github.com/ktquez/vue-head
