### ISSUE TITLE
舊的網址透過 404.html 轉向

### ISSUE THREAD

**Issue by audreyt** [g0v/vue.vtaiwan.tw#41]
例如 https://vtaiwan.tw/closelyheld/init/ 未來要重導向到 https://vtaiwan.tw/topic/closelyheld/

概念應該就是用 404.html，只留第一個 part （`closelyheld`），然後加上 `/topic/` 前綴即可。

**Comment by youchenlee** [comment]
已於 f6388ed 處理，觀察中。

**Comment by chairco** [comment]
回報一下看起來很 ok 。

**Comment by youchenlee** [comment]
thanks @audreyt and @chairco 
issue closed
