### ISSUE TITLE
聯絡我們頁面重新整理後網址會導向錯誤位置

### ISSUE THREAD

**Issue by chairco** [g0v/vue.vtaiwan.tw#42]
不是什麼大問題，因為應該很少人會這樣做。
在 http://vue.vtaiwan.tw/Contactus 這頁面下，如果你按重新整理，頁面會被導到 http://vue.vtaiwan.tw/topic/Contactus （網址中被加入 /topic/）。

在 https://vtaiwan.tw/Contactus 這樣做也會有同樣狀況。

**Comment by john5601** [comment]
get-route.js 沒加到/contactus
