### ISSUE TITLE
首頁需要個「提示下捲看更多」的元件

### ISSUE THREAD

**Issue by jokeum** [g0v/vue.vtaiwan.tw#43]
options: 閱讀更多按鈕、向下動態箭頭、進度條…

**Comment by chairco** [comment]
http://cbopp-art.github.io/anchor/
http://jsfiddle.net/psrRQ/4/
可以像是上面範例，透過設定 anchor（錨點）來跳到指定頁面。這樣可以避免 user 在瀏覽網頁時迷失在某些頁面而忽略下面內容。

**Comment by jokeum** [comment]
fix at c4b4848a264082d8e438c0aa3805006841a50cfc
