### ISSUE TITLE
在 News 下面 加一個 "Around the Globe" 區塊

### ISSUE THREAD

**Issue by shuyanglin** [g0v/vue.vtaiwan.tw#46]
放舊網站的「重要觀測」內容
http://www.vtaiwan.org.tw/international.aspx?tp=C&no=83

之後會由FB上稿
程式抓的關鍵字叫做【國際觀測】

預覽與細節頁面的文字內容維持原樣，
樣式可以重新設計。

@AvrossHsiao

**Comment by john5601** [comment]
已在首頁加入
樣式待調整
換頁還沒做
