### ISSUE TITLE
Hyperlinks disappearing from Observations block

### ISSUE THREAD

**Issue by audreyt** [g0v/vue.vtaiwan.tw#48]
> PDPC發布、修訂個人資料電子媒介保護指南和個人資料物理上處理指南
> 新加坡個人資料保護委員會（PDPC）發布一份新指南「個人資料時防止意外披露指南」(Guide to Preventing Accidental Disclosure)，為組織提供在處理和發送個人資料時防止意外洩露的知識，提供以下指導： < >< >< >< >< >

Note the `< >< >< >< >< >`

**Comment by smith02620** [comment]
http://www.vtaiwan.org.tw/international_detail.aspx?no=83&d=31
在原始vtaiwan.org 內文為< >< >< >< >< >
我等等把他刪除
