### ISSUE TITLE
Allow deeplink for tabs on topic pages

### ISSUE THREAD

**Issue by patcon** [g0v/vue.vtaiwan.tw#50]
I am finding myself often trying to share the nicely designed topic pages with english speakers. I am fine sharing the non-English page, but I feel that English viewers are most likely to explore deeper if they can land directly on the "timeline" tab.

I could alternatively share the transcript or youtube links together, but it makes the whole vtaiwan project feel "less coherent" when I am forced to introduce it that way. I would much prefer to link to vtaiwan.tw itself.

I would love to see the ability to use a link like https://vtaiwan.tw/topic/airbnb/#timeline

Thanks!

**Comment by jokeum** [comment]
Thanks to your advice. I've just added this feature here. https://github.com/g0v/vue.vtaiwan.tw/commit/324d677d9218f5b91e717f15979be28fe9e42ac6
