### ISSUE TITLE
[ Redesign suggestions #1 ] Proposal tab

### ISSUE THREAD

**Issue by yesiamjo** [g0v/vue.vtaiwan.tw#56]
![screen shot 2017-06-07 at 11 54 24](https://user-images.githubusercontent.com/16150690/26872785-16989410-4b78-11e7-8260-43d14d73a80a.png)

1. 修改進度上的文案內容
2. 按下的顏色改為紅色並修改形狀

**Comment by jokeum** [comment]
文案的內容怕會太長，在手機上可能會需要斷行？

**Comment by yesiamjo** [comment]
@jokeum 確實，或將文案當中的「的」去掉呢？會不會相較而言比較難讓使用者快速理解？
* 依現有設計，現行手機版（圖一）的設計本來就為直行故不需擔心，而平板的設計（圖二）確實本來有斷行，但將字數縮為六字以內對排版較有利。
圖一
![screen shot 2017-06-12 at 15 33 53](https://user-images.githubusercontent.com/16150690/27036468-2d333e3a-4f85-11e7-9ebb-773e086f856c.png)
圖二
![screen shot 2017-06-12 at 15 33 36](https://user-images.githubusercontent.com/16150690/27036465-2b71bfd6-4f85-11e7-916d-4b1d8d849d7e.png)

**Comment by yesiamjo** [comment]
感謝！目前線上版（圖一）與部分設計細節（顏色、形狀等）有些落差。詳見圖二或連結：https://invis.io/VWC5OMF8A#/238875740_Proposal_Tab

（圖一）
![screen shot 2017-06-14 at 10 14 17](https://user-images.githubusercontent.com/16150690/27122322-9cb446b2-50ea-11e7-8a70-9c5824828e62.png)
（圖二）
![proposal tab](https://user-images.githubusercontent.com/16150690/27122413-e91034a8-50ea-11e7-87f7-825d346e24ec.png)

**Comment by jokeum** [comment]
已修正，但字型的部份可能會因使用環境不同有些差異…可能使用網路字型比較一致。

**Comment by yesiamjo** [comment]
建議使用網路字型指的是紅色數字的部分嗎？（目前看到使用的是 roboto？）
另外，發現當時建議的大小有時會不易閱讀，試試將紅色數字的尺寸將 8.5 em（圖一）改為 5 em（圖二）？
（圖一）
![screen shot 2017-07-04 at 16 27 06](https://user-images.githubusercontent.com/16150690/27834108-e8c66ecc-60d5-11e7-90da-d3a0eaf99d37.png)
（圖二）
![screen shot 2017-07-04 at 16 26 55](https://user-images.githubusercontent.com/16150690/27834111-ea70a756-60d5-11e7-9e27-76448b766605.png)
