### ISSUE TITLE
[ Redesign suggestions #2 ] Progress bar

### ISSUE THREAD

**Issue by yesiamjo** [g0v/vue.vtaiwan.tw#57]
![screen shot 2017-06-08 at 17 32 16](https://user-images.githubusercontent.com/16150690/26937033-91b46edc-4c70-11e7-9af9-46a8e9251a19.png)

說明：將原本進度條改為圓形，增加時間感（非進度感）並節省空間

**Comment by jokeum** [comment]
That is better, thanks.

**Comment by yesiamjo** [comment]
謝謝！目前線上版（圖一）與設計示意有落差，故補充參考資訊（圖二）/ 連結：https://invis.io/VWC5OMF8A#/238878259_Progress_Bar

（圖一）
![screen shot 2017-06-14 at 10 50 36](https://user-images.githubusercontent.com/16150690/27123913-90fb928a-50ef-11e7-9279-59475c7bf547.png)
（圖二）
![progress bar](https://user-images.githubusercontent.com/16150690/27123798-3dda71a2-50ef-11e7-9808-428c4d76b310.png)

**Comment by jokeum** [comment]
已修正，不過顯示上有些技術問題，像是第一次 load 進來時圈圈顯示會失敗，有待解決。（js lifecycle problem）

**Comment by jokeum** [comment]
目前顯示上應該是沒問題了，只是空心環形比較難做，先用實心圓形代替 XDDD

**Comment by yesiamjo** [comment]
謝謝！請問能否把內圓的色碼改為 #000000（圖ㄧ），並稍微縮小尺寸（圖二）是否能更凸顯藍色的剩餘時間軸，目前看起來較細有點不清楚
（圖一）
![screen shot 2017-07-01 at 17 40 44](https://user-images.githubusercontent.com/16150690/27763475-ad92f3b4-5e84-11e7-83ea-751a6d4ba56e.png)
（圖二）
![screen shot 2017-07-01 at 17 44 44](https://user-images.githubusercontent.com/16150690/27763504-12d20bc0-5e85-11e7-9480-7e975888db3e.png)

**Comment by jokeum** [comment]
updated
