### ISSUE TITLE
Responsive 欄位會互相蓋到

### ISSUE THREAD

**Issue by yesiamjo** [g0v/vue.vtaiwan.tw#59]
螢幕寬度在 990px 以下時，proposals 欄位過長會與 news 和 around the globe 內容互相蓋到
![screen shot 2017-07-01 at 17 30 58](https://user-images.githubusercontent.com/16150690/27763527-63b2f158-5e85-11e7-8f53-a6d88a6335ea.png)

**Comment by jokeum** [comment]
似乎在各大瀏覽器上無法重現耶…想問使用環境為何？

**Comment by yesiamjo** [comment]
是最新版本的 Chrome Version 59.0.3071.115 ，
但剛剛再連幾次後就沒跑版了，若下次再有問題再回報上！
