### ISSUE TITLE
Call to action on social-enterprise page

### ISSUE THREAD

**Issue by audreyt** [g0v/vue.vtaiwan.tw#60]
https://vtaiwan.tw/topic/social-enterprise/

在意見徵集期， “參與討論” 可以更顯眼，目前按下去是空的，應嵌入（或彈出） typeform。

另外用 Firefox 看「議題時間軸」最新的在最上方（OK），但 Safari 看時，最新的在最下方。

**Comment by jokeum** [comment]
add typeform at d7c0903fd99fed6e5b2abe4c0cadfd3154847d16

**Comment by jokeum** [comment]
should be fixed in 10fc9ac
