### ISSUE TITLE
[ Redesign suggestions #3 ] Label 更改

### ISSUE THREAD

**Issue by yesiamjo** [g0v/vue.vtaiwan.tw#61]
- 「議題時間軸」改為「時程與相關連結」
- 「相關連結」改為「相關外部連結」（依實際 responsive 情況斟酌）
![screen shot 2017-08-09 at 11 56 17](https://user-images.githubusercontent.com/16150690/29116020-d3938fcc-7cf9-11e7-81b8-0ea3c13f1873.png)

- CTA 按鈕改為「進入討論」

![screen shot 2017-08-09 at 11 58 44](https://user-images.githubusercontent.com/16150690/29116118-29dbe5d2-7cfa-11e7-87c9-fd21e639340b.png)

**Comment by jokeum** [comment]
Labels updated
