### ISSUE TITLE
[ Redesign suggestions #6 ]  若意見徵集到期，文案以「徵集結束」取代「剩 0 天」

### ISSUE THREAD

**Issue by yesiamjo** [g0v/vue.vtaiwan.tw#64]
如圖，此修改可避免使用者混淆（以為仍可提供意見），可視情況調整文案內容。
![screen shot 2017-08-23 at 00 28 33](https://user-images.githubusercontent.com/16150690/29576349-10e5113e-879a-11e7-9acc-0fad7d9a6064.png)

**Comment by youchenlee** [comment]
ebce879 這個修改，可能會導致「最後一天」被顯示為「徵集結束」
待處理

**Comment by yesiamjo** [comment]
有辦法使「最後一天」維持原樣，並只讓已過期的議題改為「徵集結束」嗎？

**Comment by youchenlee** [comment]
Hi @yesiamjo 沒問題。不確定會不會有這問題，待觀察，所以先讓 issue open 著。
就算有，只要改程式把它處理好即可。

非常謝謝你的建議。

**Comment by yesiamjo** [comment]
剛剛沒看清楚回覆 不好意思 謝謝修改！ :-)
