### ISSUE TITLE
爬不到後端資料

### ISSUE THREAD

**Issue by yueky** [g0v/vue.vtaiwan.tw#85]
前台好像抓不到 Discourse 的資料
<img width="1280" alt="截圖 2021-07-22 上午11 35 30" src="https://user-images.githubusercontent.com/17798068/126691359-1411f14c-3681-4d5b-a953-0c43e6733e5e.png">

**Comment by jokeum** [comment]
看起來是 talk.vtaiwan.tw 的憑證 22 天前過期了…

**Comment by jokeum** [comment]
fixed by @audreyt
